### ISSUE TITLE
Sporadische soorten

### ISSUE THREAD

**Issue by jrhillae** [inbo/prius#12]
"Bovendien zouden we graag die soorten in een lijstje krijgen die in sommige kalenderjaren wél, maar in andere niét zijn waargenomen (‘sporadische’ soorten). Dit vraagt allicht een aangepaste workflow."

Ik zet dit in aparte issue want dit gaat ook over temporeel voorkomen en niet alleen ruimtelijk. 

@bramdhondt : Bedoel je hierbij waargenomen in Vlaanderen, wel en niet tss kalenderjaren? Wat ik vrij makkelijk kan achterhalen is per soort het aantal jaren sinds 2015 waarin het voorkwam. Maar dit op zich is niet voldoende. Het moet dus ook een keer aanwezig en dan weer afwezig zijn. Of wat zijn de exacte criteria (ruimtelijk en temporeel) van sporadisch waarop ik moet filteren? Kan je iets specifieker zijn?

Bedankt

**Comment by bramdhondt** [comment]
Ik bedoel inderdaad in Vlaanderen (Vlaams Gewest).

Sporadisch betekent inderdaad dat er ná een kalenderjaar waarin de soort is vastgesteld, ook een kalenderjaar is waarin ze niét is vastgesteld.

Voorbeelden (elk cijfer is aan- of afwezigheid, van 2015 t.e.m. 2022, dus acht cijfers):

- _Vespa_ : 00111111 = aanwezig
- Soort 2 : 01001001 = sporadisch
- Soort 3 : 10111111 = sporadisch
- Soort 4 : 11111111 = aanwezig
- Soort 5 : 00000000 = afwezig
- Soort 6 : 11110000 = sporadisch (al is dit discutabel)
- Soort 7 : 00000001 = aanwezig (al is dit discutabel)
- ...

_Does that make sense?_

Probeer zo te scripten dat we het startjaar (nu: 2015) kunnen variëren. We zullen namelijk even moeten evalueren of de tijdsspanne 2015-2022 voldoende breed is om de variatie te vatten.

**Comment by jrhillae** [comment]
@bramdhondt : Ok.

**Comment by jrhillae** [comment]
@bramdhondt : based on the cube '"https://zenodo.org/record/4299976/files/be_alientaxa_cube.csv?download=1" I created  plots in data/output/sporadic_species representing occupancy per year. This might be handy as sporadic species do not have a high occupancy when they occur? 

If I have the correct link of the cube (also including observations of 2021) I will remake these figures.
