### ISSUE TITLE
Toevoeging Misgurnus bipartitus aan PrIUS-soortenlijst

### ISSUE THREAD

**Issue by bramdhondt** [inbo/prius#19]
Vraag van de opdrachtgever: "Ik wou ook nog vragen om _Misgurnus bipartitus_ in de niet-unielijstsoorten mee te nemen. Deze info kan ook nuttig zijn voor het herwerken van LIFE Misgurnus."

Uit Brys (2020, NatuurFocus) haal ik dat volledige naam is: _Misgurnus bipartitus_ (Sauvage & Dabry de Thiersant 1874). Dit is GBIF-code [2367913](https://www.gbif.org/species/2367913), met enkel Belgische _records_. Daar wordt ze wel als synoniem gesteld van [_Misgurnus mohoity_](https://www.gbif.org/species/2367911) (2367911), met ook inheemse _records_.

- [x] Toevoeging aan soortenlijst (Bram).
- [x] Climate matching (Sander)?

**Comment by SanderDevisscher** [comment]
@bramdhondt ik zal de climate matching wel op mij nemen. Met amper 45 georeferenced records ([Misgurnus mohoity](https://www.gbif.org/species/2367911)) zal dit een walk in the park zijn voor de functie.
