### ISSUE TITLE
Verspreidingskaartjes obv Occurrence cube

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/prius#2]
https://zenodo.org/record/6341688#.YvC31HZByUk

- [ ] 1x1km
~- [ ] 5x5km~
- [ ] 10x10km
- [ ] % in speciale bescherming gebied
- [ ] % in perimeter rond waterloop
- [ ] background layer spa

@damianooldoni is it possible to update the occurrence cube ?

**Comment by SanderDevisscher** [comment]
@timadriaens plak je hier een voorbeeld van de manageability kaartjes?

**Comment by SanderDevisscher** [comment]
@bramdhondt @timadriaens een idee voor date cutoffs ?

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher: yes, it is possible to update the cube. I was almost there. I have just to finalize it. I try to do it in the next days, I hope next week.

superb

**Comment by bramdhondt** [comment]
@SanderDevisscher @timadriaens - Sander, om op je vragen te antwoorden.

- Ik zou de data nemen vanaf **2015**, de datum van inwerkingtreding van de verordening ("Deze verordening treedt in werking op 1 januari 2015") (effectieve inwerkingtreding was wel later, met publicatie van de 1ste lijst, maar geen erg). Andere oplossing had geweest te baseren op de T0-rapportage, die uitgaat van 2000, maar dat gaat mijn inziens té ver terug voor de doelstellingen nu.
- Ik zie geen probleem in gebruik van enkel **1-op-1** en, waar nuttig, **10-op-10** (EEA). Het lijkt me niet de moeite nieuwe structuren op te zetten louter om 5-op-5 mogelijk te maken.

**Comment by SanderDevisscher** [comment]
https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2/gis-files/belgium-shapefile/at_download/file

**Comment by SanderDevisscher** [comment]
https://zenodo.org/record/4299976/files/be_alientaxa_cube.csv?download=1

**Comment by bramdhondt** [comment]
@jrhillae -- Dag Jasmijn, gezien jouw beschikbaarheid (vanaf 4 juli) en het veldwerk van Sander, laat ik jou hier een doorstart maken. We kloppen onderstaande af op 5 juli.

De eerste twee grotere R-taken zijn **(1) verspreidingskaartjes** opmaken voor de PrIUS-soorten; **(2) de TrIAS-GAM-methode** toepassen op de PrIUS-soorten. Dit issue behandelt het eerste.

De verspreidingskaartjes geven per soort voor (enkel) **het Vlaamse Gewest** de **1-op-1-km-rastercellen** (EEA-raster) weer waarbinnen de soort sinds **1 januari 2015** is aangetroffen. We nemen genoegen met de verspreidingsdata van **GBIF**.

De soorten worden weergegeven in `data\input\prius_species_list_primary_vXX-XX-XX.csv`. Het zijn de **GBIF-codes** in dat bestand die als feitelijk vertrekpunt dienen. Het is de bedoeling dat **voor elke Nederlandstalige naam** in dat bestand **één kaartje** wordt opgemaakt. Immers zijn er meerdere GBIF-codes aan eenzelfde 'soort' gebonden. Dat zijn ofwel synoniemen (bv. _Lespedeza cuneata_ en _L. juncea_) of verzamelsoorten (bv. de invasieve duizendknopen, een groep van drie soorten, bovendien elk met zijn eigen synoniem).

Soorten die nooit zijn waargenomen in die periode (**'afwezige' soorten**), behoeven geen verspreidingskaartje. Zij moeten wel als een **lijst** worden bijgehouden (ten behoeve van het rapport).

Bovendien zouden we graag die soorten in een lijstje krijgen die in sommige kalenderjaren wél, maar in andere niét zijn waargenomen (**‘sporadische’ soorten**). Dit vraagt allicht een aangepaste _workflow_. 

Vormelijk zie ik (voorlopig) niet veel eisen. Ik zou de _gegevens_ _rood_ kleuren. De _titel_ is best de _Nederlandstalige naam_. De _achtergrond_ kunnen de _gemeentegrenzen_ zijn en/of de _grotere waterlopen_. De figuren krijgen een _grootte / resolutie_ die gepast is voor publicatie als meerdere figuren (6 à 8) per blad (bijlage bij rapport).

Wat de verspreidingsdata betreft, laat ik je de keuze of je via de _cube_ werkt, of niet. Ik ben daar minder mee vertrouwd, wat voor mij de afhankelijkheid van anderen verhoogt (Damiano, Sander). Toch is dat mogelijk nuttig (zelfs nodig?) in licht van de TrIAS-GAM-analyse. Hoe dan ook vind je binnen de _branch_ een aanzet van een cube-gabaseerd script (`cubeBased_spread_maps.Rmd`, Sander) en van een niet-cube-gebaseerd script (`alternative_spread_maps.Rmd`, mezelf).

Ik laat je zelf de _commits_ formuleren.

**Comment by jrhillae** [comment]
@SanderDevisscher en @bramdhondt : Ok to work with the cube? As we said before, the only downside is that most recent data is not included. I think the last update of the cube occured in March.

**Comment by bramdhondt** [comment]
@jrhillae (@SanderDevisscher) : helemaal goed om met de _cube_ te werken. De voordelen wegen door op de nadelen.

Ter info, ik ben vorige week zelf aan de slag gegaan met verspreidingskaartjes voor muntjak. Ik heb dat script van de fis-projecten _repo_ opgeschoond, en alles naar _sf_ omgezet (waar het voorheen in _sp_ stond). Mocht je er inspiratie in vinden: https://github.com/inbo/fis-projecten/blob/278_Muntjak/Exoten/muntjak/scripts/Muntjak_verspreiding.Rmd

**Comment by bramdhondt** [comment]
@jrhillae -- De volgende soorten zijn louter marien, en hoeven in dit issue in feite niet worden behandeld: (1) _Plotosus lineatus_, (2) _Rugulopteryx okamurae_.

**Comment by jrhillae** [comment]
@bramdhondt , @SanderDevisscher : I am working in branch '2_verspreidings_kaartjes' in file CubeBased_spread_maps_jasmijn which is based on the script of Sander.

Please, let me know if you want me to change this. So far, everything is clear and the script of Sander works fine so no questions yet.

**Comment by jrhillae** [comment]
@SanderDevisscher : Voor dit onderdeel heb ik een laag nodig van SBZ, waar kan ik die vinden? Of overlapt dit met TrIAS? 

Zie uitleg van Bram hierboven: 
"Tenslotte willen we ook van elke soort weten welk aandeel van de bezette hokken binnen Speciale Beschermingszones vallen ("SBZ", i.e. het Natura2000-netwerk). Dat lijkt me een overlay, al zou je ook even kunnen kijken / navragen of dit niet ook één van de TrIAS-indicatoren is ([Protected areas analysis](https://trias-project.github.io/indicators/)). Ook relevant: het aandeel van hokken binnen SBZ dat bezet is door de soort."

**Comment by bramdhondt** [comment]
> @bramdhondt : De Prius species list verschilt blijkbaar tss branch 2_verspreidingskaarjtes en de master. Vervang ik de soortenlijst op deze branch door de soortenlijst van de master?

@jrhillae : inderdaad, je dient je te baseren op de PrIUS-soortenlijst van de _master_. Enkel daar wordt de meest up-to-date versie bijgehouden.

Let op: ik kwam er zonet met Sander op uit dat er nog wat verbeterwerk aan is. Dat wordt behandeld in een nog op te zetten _issue_ (vannamiddag, door mij).

Concreet betekent dit voor jou: óf wachten om te runnen (tot bovengenoemde _issue_ is gepusht); of voortwerken met provisionele data (_pro forma_) om dan later eens finaal te laten lopen.

**Comment by bramdhondt** [comment]
@jrhillae : de aanpassingen aan de PrIUS-soortenlijst zijn aangepast op de _master_. _Good to go!_

**Comment by jrhillae** [comment]
@bramdhondt : First version of spread maps are available in https://github.com/inbo/prius/tree/2_verspreidings_kaartjes/data/output/spread_maps/. I will set resolution to dpi 200 and also add watercourses to the background of the figures. What dimensions would be best? I can als adapt this later on, if necessary. Remarks are welcome.

**Comment by bramdhondt** [comment]
@jrhillae : dat ziet er al goed uit!

**Achtergrond**: de waterlopen zijn maar voor een deel van de soorten relevant, dus ik kom op die keuze terug. Gezien we de nadruk leggen op het natuurbeleid, en daar ook cijfers over presenteren, is het misschien illustratiever om de gecombineerde (de unie van) habitat- en vogelrichtlijngebieden te gebruiken. Zie hieronder. In een _licht_, zacht _groen_, _niet omrand_.

Op [deze link](https://overheid.vlaanderen.be/Webdiensten-Overdrachtdiensten) zie ik daar geen WFS'en van terug. (Opm. de "WFS (...) Natura 2000 Habitatkaart" is niet hetzelfde. Deze toont waar Natura 2000 habitat is herkend, maar dat kan ook buiten de afgebakende habitatrichtlijngebieden zijn). De kaarten circuleren wel op de INBO-schijven.

![afbeelding](https://user-images.githubusercontent.com/78358923/182552282-b6175293-d99b-4a94-b584-72a60e711624.png)

Denk je dat dit haalbaar is?

Ik twijfel nog of we voor (een deel van) de aquatische soorten misschien wél de waterlopen nemen als achtergrond. Ik begrijp dat dat onderscheid script-gewijs wel niet zo dankbaar is.

**Formaat**: Uiteindelijk dienen de figuren enkel voor druk. Breedte A4 (21 cm) minus marge (5 cm) geeft breedte van 16 cm.

**Comment by bramdhondt** [comment]
@jrhillae -- Ik voegde binnen deze _branch_ in de input-map `aqua_vs_terr.csv` toe. Voor elke Nederlandstalige naam is aangegeven of dit een eerder aquatische (AQUA) of terrestrische (TERR) soort is. Bedoeling is dat het script voor de kaartjes daar een tweedeling kent: voor 'AQUA' is de achtergrond gelijk aan de waterlopen, voor 'TERR' de Natura2000-gebieden (kaart hierboven).

Je zult dus wel nog even moeten _join_'en op soortsnaam. Normaal zou dat geen problemen mogen geven (soortsnaam is overgenomen uit `prius_species_list.csv`). Maar let op: ik ontdekte wel dat er achter sommige namen per abuis een spatie staat.

Beschouw dit als experimenteel, want ik ben nog niet volledig overtuigd van de keuze voor de waterlopen als achtergrond. De ecologisch belangrijkste waterlopen zijn namelijk ook Natura2000, zodat het wel steek houdt bij dié ene keuze te blijven. Maar het zou toch goed zijn de beide opties in het script te hebben.

- [ ] Tweedeling waterlopen vs. Natura2000 als achtergrond.

Daarenboven zou het goed zijn de provinciegrenzen te hebben (die sprak ik al eerder via WFS aan).

- [ ] Provinciegrenzen als achtergrond.

Dan denk ik dat we er zijn. Best eerst wat voorbeelden maken alvorens we het op alle soorten loslaten.

**Comment by bramdhondt** [comment]
@jrhillae -- Wat laatste input om de kaartjes af te werken.

- [ ] de figuur zelf hoeft geen titel (soortnaam).
- [ ] volgens voorlopig ontwerp komt de figuur met een hoogte van 6,4 cm en breedte van 15 cm in het rapport.
- [ ] in de bestandsnaam mag `plot_` vervallen. De soortnaam alleen is makkelijker om mee te werken in verdere stappen.
- [ ] de achtergrond van de provincies mag wat lichter (grijs): `#f0f0f0` (RGB: 240, 240, 240)
- [ ] de grenzen van de provincies mogen ook een eenheidje dunner
- [ ] het groen van Natura 2000 mag: `#a4e98f` (RGB: 164, 233, 143)

Hieronder een _render_ volgens huidig ontwerp van rapport ! Van zodra klaar, mag je een _pull request_ zetten. Ik pik het van daaruit op.

![afbeelding](https://user-images.githubusercontent.com/78358923/183020176-67372921-1c58-465a-b078-ee6a1342e91c.png)

**Comment by bramdhondt** [comment]
@jrhillae -- Wat de aanwezigheid van de soorten binnen Natura2000 betreft, stel ik het volgende voor. (I.t.t. eerder bericht, excuses. Laten we het op voortschrijdend inzicht houden.) Wat mij betreft kan dit binnen deze _issue_, of als nieuwe _issue_ (deze issue dan of te sluiten op de kaartjes).

Ik zie 6 relevante variabelen per soort:

1. Het percentage door de soort bezette hokken dat binnen _habitatrichtlijngebied_ valt (of er gedeeltelijk mee overlapt).
2. Het percentage door de soort bezette hokken dat binnen _vogelrichtlijngebied_ valt (of er gedeeltelijk mee overlapt).
3. Het percentage door de soort bezette hokken dat binnen _Natura2000_ valt (of er gedeeltelijk mee overlapt). (Natura2000 = unie van habitatrichtlijngebied en vogelrichtlijngebied.) (Doordat sommige locaties binnen beide vallen, is deze variabele niet zomaar de som van de vorige twee variabelen.)
4. Het percentage van het _habitatrichtlijngebied_ dat bezet is door de soort.
5. Het percentage van het _vogelrichtlijngebied_ dat bezet is door de soort.
6. Het percentage van _Natura2000_ dat bezet is door de soort.

Bemerk dat voor variabelen 4-6 een kunstgreep nodig is: de kaart zal moeten gerasterd worden, volgens hetzelfde 1-km²-raster als van de _cube_. Van daaruit wordt dan bekeken hoeveel van die cellen ook bezet zijn door de soort. Het betekent dat we wat buiten de randjes kleuren, maar dat lijkt me verdedigbaar.

De variabelen worden best aangeleverd in een tabel (per soort, 6 kolommen voor 6 variabelen). We willen zeker ook eens variabelen 3 en 6 tegenover elkaar uit zetten, over de soorten heen. Dat kan interessant worden.

Indien mogelijk, graag tegen midden volgende week (ong. 10/08).

**Comment by timadriaens** [comment]
Die oefenibg is al gebeurd ikv TrIAS dus geen kubstgrepen nodig denk ik. Zie deze dataset op zenodo https://zenodo.org/record/3784227# dus de lojst van km hokken in n2000 is bekend.Yu063qRcIzY. Die groene achtergrond lijkt me ook niet het volledige n2000 te zijn? Persoonlijk denk ik dat n2000, provincies en hoofdwaterlopen geboeg aibn als achtergrond.

**Comment by jrhillae** [comment]
@bramdhondt : Final spread maps are pushed to this branch. I need to finalize extra calculations before I submit a pull request

**Comment by jrhillae** [comment]
> https://zenodo.org/record/4299976/files/be_alientaxa_cube.csv?download=1

@bramdhondt, @SanderDevisscher : Is this the version of the cube I am supposed to use? For the moment the figures are based on this input, but includes only data until 2020. 2021 is not included.

**Comment by jrhillae** [comment]
> Die oefening is al gebeurd ikv TrIAS dus geen kunstgrepen nodig denk ik. Zie deze dataset op zenodo https://zenodo.org/record/3784227# dus de lijst van km hokken in n2000 is bekend.Yu063qRcIzY. Die groene achtergrond lijkt me ook niet het volledige n2000 te zijn? Persoonlijk denk ik dat n2000, provincies en hoofdwaterlopen genoeg zijn als achtergrond.

Ik vind in de files op deze link geen lijst terug met km hokken in Natura2000 gebied. Elke SiteCode verwijst naar het Natura2000 gebied zelf.

**Comment by bramdhondt** [comment]
@jrhillae -- Ok, lijkt me enkel kwestie van de juiste functie te vinden. `st_join(Natura2000, vla_1km, left = FALSE)` ?

@timadriaens -- "Die groene achtergrond lijkt me ook niet het volledige n2000 te zijn?" Laat weten wat je denkt dat hier ontbreekt. We willen dit juist hebben.

**Comment by jrhillae** [comment]
> @jrhillae -- Ok, lijkt me enkel kwestie van de juiste functie te vinden. `st_join(Natura2000, vla_1km, left = FALSE)` ?
> 
> @timadriaens -- "Die groene achtergrond lijkt me ook niet het volledige n2000 te zijn?" Laat weten wat je denkt dat hier ontbreekt. We willen dit juist hebben.

De finale kaartjes hebben veel meer groen dan het voorbeeld hierboven. Wss is dat van hierboven een tijdelijk kaartje met enkel vogelrichtlijngebied, in data/output/spread_maps ziet het groen er veel uitgebreider uit.

**Comment by bramdhondt** [comment]
Ja, haha, dat kaartje was mijn eigen inkleuring, he (Paint, t.b.v. het kleurenpallet). :-)

**Comment by jrhillae** [comment]
> Ja, haha, dat kaartje was mijn eigen inkleuring, he (Paint, t.b.v. het kleurenpallet). :-)

ok, dan is dat al opgelost ;)

**Comment by jrhillae** [comment]
@damianooldoni : Op basis van de GBIF_codes in deze file ('https://raw.githubusercontent.com/inbo/prius/f52fc4e0bb060d5a3d372d1650502602a0a562fd/data/input/prius_species_list.csv') moet ik data selecteren uit de cube. Gebruik ik het beste de alien cube met taxonkeys (https://zenodo.org/record/5819028/files/be_alientaxa_cube.csv?download=1) of de species cube met specieskeys (https://zenodo.org/record/6341688/files/be_species_cube.csv?download=1)? Wat is het verschil precies tussen beide? 

Bedankt

**Comment by damianooldoni** [comment]
De alien cube bevat niet enkel soorten, maar ook subsoorten, varieties ezv. Niet veel, maar toch... De cube bevat ook enkel de taxa in de "unified checklist" (https://www.gbif.org/dataset/6d9e952f-948c-4483-9807-575348147c7e)
De species cube aggregeert, zoals de naam zegt, op soortenniveau en bevat ALLE soorten, niet enkel de exoten.

Aangezien dat ik de alien cube gebruik voor de [TrIAS indicatoren](https://trias-project.github.io/indicators/index.html), dan kan al genieten van de preprocessing workflow die ik al heb geschreven: zie https://trias-project.github.io/indicators/05_occurrence_indicators_preprocessing.html. De output ervan (te groot voor GitHub) is ons startpunt (en dus ook jullie) voor de berekening van al de indicatoren.

Natuurlijk kan je een soortgelijke workflow toepassen aan de species cube uiteraard.

Ik hoop dat die helpt.

**Comment by jrhillae** [comment]
@timadriaens : I found the file: https://github.com/trias-project/indicators/blob/master/data/interim/intersect_EEA_ref_grid_protected_areas.tsv

**Comment by damianooldoni** [comment]
Yes, @jrhillae, that's a good one and it is the output of this workflow analyzing the presence of IAS in protected areas: https://trias-project.github.io/indicators/10_species_observations_occupancy_in_protected_areas.html

The only point is that this file has not been updated: as you see last commit is from 2020. I should update these very last workflows (about PAs) based on the very last version of the cube as well.

**Comment by damianooldoni** [comment]
I was wrong in my comment this morning. The file pointed out by @timadriaens didn't change after updating the cube as it is the intersection of the EEA 1kmx1km grid with the Natura2000 proteced areas. It's actually the output of this workflow: https://trias-project.github.io/indicators/09_define_overlay_grid_belgium_with_protected_areas.html
I was also wrong when I said that I didn't update these very last workflows related to protected areas: I did it actually! 💪 

What I have to do now is to update the data deposited at zenodo: https://zenodo.org/record/3784227.

**Comment by jrhillae** [comment]
> I was wrong in my last [comment](https://github.com/inbo/prius/issues/2#issuecomment-1209135490), this morning. The file pointed out by @jrhillae in [previous comment](https://github.com/inbo/prius/issues/2#issuecomment-1209111031) didn't change after updating the cube as it is the intersection of the EEA 1kmx1km grid with the Natura2000 proteced areas. It's actually the output of this workflow: https://trias-project.github.io/indicators/09_define_overlay_grid_belgium_with_protected_areas.html I was also wrong when I said that I didn't update these very last workflows related to protected areas: I did it actually! 💪
> 
> What I have to do now is to update the data deposited at zenodo: https://zenodo.org/record/3784227.

Good job Damiano!

**Comment by jrhillae** [comment]
@damianooldoni , @bramdhondt @SanderDevisscher : A few species are only present in species cube and not alien cube: gewone gunnera, marmerkreeft, gevlekte rivierkreeft and Afghaanse duizendknoop. For at least two of them, this is because they are not mentioned in the unified checklist. Therefore we will base the spread maps on the species cube. @damianooldoni: can the species cube also be used as input for the preprocessing of the TRIAS indicators? (if I rename the columnheaders correctly?)

**Comment by damianooldoni** [comment]
Well, the idea behind is exactly the same, yes. You will end up with slightly simplified workflows even as we don't have to take care about other taxon ranks except species.

**Comment by jrhillae** [comment]
@bramdhondt, @SanderDevisscher : a short summary 

1. spread maps: 
- Code is normally ok. You could review this for mistakes (script is here: r-scripts/cubeBased_spread_maps_jasmijn.Rmd).
- Output Maps are located in data/output/spread_maps/
- Species present and species not present are listed in data/output
- Taxonkeys not present are listed in data/intermediate/taxonkeys_not_in_cube_jas.csv
- Remark: the species cube was to heavy to push to the git. This will give an error when running the script. I needed to download it locally (making connection with zenodo within the script was too slow). So maybe best to [download](https://zenodo.org/record/6341688/files/be_species_cube.csv?download=1) the most recent version of the species cube and put it in the folder data/input before running it?

2. Sporadic species:
 - Code is normally ok. You could review this to be sure (script is here: r-scripts/cubeBased_sporadische_soorten.Rmd).
 - Output is here: https://github.com/inbo/prius/tree/2_verspreidings_kaartjes/data/output/sporadic_species/

3. Natura2000:
 - Code is here: r-scripts/cubeBased_IAS_Natura2000.Rmd. Would it be possible to carefully check this code? And also check if I interpreted the columnheaders ('% in' versus 'bezet') correctly? The natura2000 - EEA ref grid overlay is based on [the file](https://github.com/trias-project/indicators/blob/master/data/interim/intersect_EEA_ref_grid_protected_areas.tsv) of Damiano. 
 - Output file is here: data/output/occurence_Natura2000.csv

If you have no further remarks on the code or output I can perform a pull request.

**Comment by bramdhondt** [comment]
@jrhillae -- Ziet er allemaal zeer goed uit. Bedankt voor het uitstekende overzicht.

Ik heb de volgende wijzigingen aangebracht:

1. in script van de kaartjes heb ik je opmerking gezet van de zware species cube. Zo worden we herinnerd aan je voorgestelde aanpak om de cube in de input-folder te plaatsen alvorens te runnen.
2. in script van de sporadische soorten heb ik workflow ingewerkt om alle data overheen de soorten weg te schrijven. Zie [hier](https://github.com/inbo/prius/blob/2_verspreidings_kaartjes/data/output/sporadic_species/sporadische_soorten.csv) voor output.

De output inzake Natura2000 ziet er allemaal logisch uit (alles volgens verwachtingen, geen rare zaken), dus ik vertrouw er voorlopig op dat het script juist zit.

Je kan overgaan tot een pull request. Het volstaat om mij als reviewer aan te duiden.

We weten dat er nog enkele specifieke zaken scheef zitten (bv. _Vespa_, _Ameiurus_...), maar dat doe ik liever later. Ik wil nu eerst het rapport voeden.
