### ISSUE TITLE
October : fine-tuning on species

### ISSUE THREAD

**Issue by bramdhondt** [inbo/prius#26]
@SanderDevisscher, @jrhillae

In de huidige versie van het PrIUS-rapport zijn de volgende, soortgebonden onvolkomendheden opgemerkt. Deze zouden moeten worden opgelost. Zie de fiches achteraan [het rapport](https://drive.google.com/file/d/1zhAbs-BODx4fQb-G1Rk_L49AT-4AMCt4/view?usp=sharing) ter referentie.

Het is een keuze of de aanpassingen helemaal vooraan worden gemaakt, in de soortenlijst, met behoud van huidige scripts; dan wel als aparte chuncks in bestaande scripts; dan wel als aparte scripts.

Spreken jullie onderling en met mij af wie wat doet? Deadline: **woensdag 19 oktober**.

- **Aziatische hoornaar**
  - Probleem: aanwezigheid in Vlaanderen, aanwezigheid in Natura2000 en trend ontbreken. Merk op dat in de soortenlijst de ondersoort is opgenomen (cf. Verordening), i.e. _Vespa velutina nigrithorax_ de Buysson, 1905 (code [6247411](https://www.gbif.org/species/6247411)). Dat was terecht voor de climate matching, maar staat ter discussie voor bovengenoemde parameters (gezien Az. hoornaar meestal als soort wordt ingegeven, en misschien ook zo in de cube zit).
  - [x] Aanwezigheid in Vlaanderen (aanwezig, sporadisch, afwezig)
  - [x] Kaartje
  - [x] Aanwezigheid in Natura2000 (6 parameters)
  - [x] Trend (Vlaanderen en Natura2000) = GAM, inclusief figuurtjes

- **Noord-Aziatische modderkruiper**
  - Probleem: aanwezigheid in Vlaanderen, aanwezigheid in Natura2000 en trend ontbreken. @jrhillae: dit komt mogelijk omdat de late toevoeging van deze soort niet was meegenomen in je scripts. Indien dat zo is, behoeft dat normaal enkel een re-run.
  - [x] Aanwezigheid in Vlaanderen (aanwezig, sporadisch, afwezig)
  - [x] Kaartje
  - [x] Aanwezigheid in Natura2000 (6 parameters)
  - [x] Trend (Vlaanderen en Natura2000) = GAM, inclusief figuurtjes

- **Lettersierschildpad**
  - Probleem: voor de trend (GAM) krijgen we "onvoldoende data" als uitkomst (voor zowel Vlaanderen als Natura2000). Dat is verwonderlijk, gezien er voldoende data voorhanden lijkt (cf. verspreidingskaartje). Eens controleren / opnieuw proberen?
  - [x] Trend (Vlaanderen en Natura2000) = GAM, inclusief figuurtjes

- **Afrikaanse klauwkikker**
  - Probleem: de soort wordt als afwezig voor Vlaanderen opgegeven. Ondertussen is ze opgedoken, en het is voor ANB ook belangrijk dit weerspiegeld te zien. Echter: de recente waarnemingen zijn waarschijnlijk nog niet doorgesijpeld naar de _cube_. Als dat zo is, dan maken we minimaal een kaartje op voor Vlaanderen o.b.v. ruwe gegevens. Haalbaarheid voor verspreiding in Natura2000, en trend, moeten dan bekeken worden.
  - [x] Kaartje
  - [x] Te evalueren: aanwezigheid in Natura2000 (6 parameters)
  - [ ] ~~Te evalueren: trend (Vlaanderen en Natura2000)~~

- **Aziatische boomwurger**
  - Probleem: komt momenteel als 'afwezig' uit de bus. Tegelijk heeft INBO in een parlementaire vraag aangegeven dat de soort beperkt voorkomt in Vlaanderen. Dit handvol waarnemingen zit ook in [GBIF](https://www.gbif.org/species/3169169), maar komt blijkelijk niet mee, mogelijks omdat de _cube_ ze nog niet oppikte. Als dat zo is, dan maken we minimaal een kaartje op voor Vlaanderen o.b.v. ruwe gegevens. Haalbaarheid voor verspreiding in Natura2000, en trend, moeten dan bekeken worden.
  - [x] Kaartje
  - [x] Te evalueren: aanwezigheid in Natura2000 (6 parameters)
  - [ ] ~~Te evalueren: trend (Vlaanderen en Natura2000)~~

- **Zwarte dwergmeerval**
  - Probleem: we weten dat de soort aanwezig is in Vlaanderen, maar dat blijkt niet uit [GBIF](https://www.gbif.org/species/2340977). @SanderDevisscher, hoe zou dat kunnen komen?
  - [ ] ~~Indien mogelijk: oplossen GBIF-data~~
  - [x] Aanwezigheid in Vlaanderen (aanwezig, sporadisch, afwezig)
  - [ ] ~~Kaartje~~
  - [ ] ~~Aanwezigheid in Natura2000 (6 parameters)~~
  - [ ] ~~Trend (Vlaanderen en Natura2000) = GAM, inclusief figuurtjes~~

**Comment by SanderDevisscher** [comment]
@bramdhondt kort antwoord waarom er geen Zwarte dwergmeerval voorkomt in de cube is omdat er in België enkel bruine zijn. 

Het lange antwoord:
Ik heb net eens met Hugo gebeld over dit probleem. Hij haalt hierover de volgende zaken aan:

1. Zwarte en bruine Amerikaanse dwergmeervallen zijn morfologisch zeer moeilijk van elkaar te onderscheiden (zie 
[INBO.R.2011.40.pdf](https://github.com/inbo/prius/files/9684519/INBO.R.2011.40.pdf)). 
2. Uit genetisch onderzoek bleek ook dat in België (Vlaanderen & Wallonië<sup>1</sup>) enkel bruine Amerikaanse dwergmeervallen voorkomen. Terwijl in Nederland beide soorten voorkomen en in Frankrijk enkel de zwarte. In welke mate dit strookt met de realiteit is moeilijk te achterhalen zonder een uitgebreid genetisch onderzoek op Europese schaal. 

Hoe het komt dat in België geen zwarte voorkomt is onbekend. Ondanks het gegeven dat beide soorten zeer waarschijnlijk geïntroduceerd zijn komt toch enkel de bruine in België voor. Een mogelijke piste te maken met de competitieve aard van de bruine waarbij de zwarte het onderspit delft. Hugo merkt ook op dat de bruine een achteruitgang kent in Vlaanderen daar hij het nu zeer moeilijk heeft exemplaren te vinden.  

<sup>1</sup>na claims dat dit enkel de zwarte zou zijn

**Comment by timadriaens** [comment]
Dat kan ik bevestigen, Hugo heeft in detail naar de vissen in GRIIS gekeken uiteraard en de zwarte staat daar niet op, bijgevolg komt die niet voor in GRIIS.

**Comment by SanderDevisscher** [comment]
Ik heb ook een vermoeden dat de issue ivm Lettersierschildpad een qwerk zouden kunnen zijn van taxonomische hiërarchieën.
Zal ik me hierin verdiepen ?

**Comment by timadriaens** [comment]
voor de roodwangen moeten we 2443002 pakken, daar zitten elegans, troostii en scripta ondersoorten onder. In waarnemingen (goed voor 7k records) zijn die effectief gemapt op de ondersoorten.

**Comment by SanderDevisscher** [comment]
Mij lijkt de "onvoldoende reptielen waarnemingen in Vlaanderen" - piste niet te kloppen. Op onderstaand kaartje zie je de reptielen waarnemingen op gbif (n=10948), dewelke mooi verspreid zijn over Vlaanderen:
![image](https://user-images.githubusercontent.com/16779320/194904290-ee6a8977-41dd-46bc-a729-75de6ee387e5.png)

De meerderheid zijn ook recente waarnemingen (>2000)
![image](https://user-images.githubusercontent.com/16779320/194905135-12f0d85b-6bbd-4689-a565-21a452b86ac4.png)

Een rariteit die me al is opgevallen is dat er maar data tot 2020 van Trachemis in de speciesCube zit terwijl er zeker waarnemingen tot dit jaar zijn op gbif.

Ik zoek verder!!

**Comment by SanderDevisscher** [comment]
Er zit volgens mij een fout in de baseline van de reptilia. Er zijn namelijk kilometerhokken waar wel trachemis waargenomen werd, volgens de cube maar waar volgens de baseline geen reptielen.  Zie issue https://github.com/trias-project/occ-cube-alien/issues/40

**Comment by jrhillae** [comment]
@SanderDevisscher , @bramdhondt : ik zal hiermee helpen vanaf woensdag. 12/10.

**Comment by bramdhondt** [comment]
@SanderDevisscher -- Dank! Heeft je aanpak ook gevolgen voor de andere soorten? Met andere woorden: pluk ik enkel de output van _Trachemys_ uit de output, en klaar is kees, of moet ik alle soorten updaten in het rapport?

**Comment by SanderDevisscher** [comment]
Ook Orconectes limosus en Koenigia hebben nu grafieken

**Comment by bramdhondt** [comment]
Alle _commits_ zijn behandeld, en de _issue_ dus afgewerkt. Ik laat de _branch_ nog openstaan voor het geval er nog gefine-tuned moet worden.

**Comment by bramdhondt** [comment]
We leerden van Damiano dat voor soorten die geen GAM-functie geven, toch een `em_status` kan worden bepaald, via een alternatieve weg, nl. de functie `apply_decision_rules()`. Althans, zo begrijp ik het. Zie https://trias-project.github.io/trias/reference/apply_decision_rules.html.

Ik zie nu dat die basis inderdaad wordt gelegd in `cubeBased_emerging_status.Rmd` (screen op `apply_decision_rules()`), maar niet wordt binnengekopt. Ik zal dat zelf even verder bekijken.

**Comment by bramdhondt** [comment]
Op vraag van Nicolas wordt de informatie van _Aedes_ best aangevuld met de data van [muggensurveillance.be](https://muggensurveillance.be/). Ik ontving de data van het ITG.

- [ ] Uitbreiden _Aedes_ met data ITG.
